apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: domino
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Domino project
  destinations:
    # explicitly deny deployments to kube-system & argocd namespaces
  - namespace: '!kube-system'
    server: '*'
  - namespace: 'arcocd'
    server: '*'
    # scope project to domino-* namespaces
  - namespace: 'domino-*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: domino-apps
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: workloads/domino/**/values.yaml
      repoURL: https://github.com/imjoshholloway/gitops-playground.git
      requeueAfterSeconds: 20
      revision: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ path[1] }}'
      name: '{{ path[1] }}'
      namespace: argocd
    spec:
      project: domino
      destination:
        namespace: '{{ path[1] }}'
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: https://github.com/imjoshholloway/gitops-playground.git
        path: '{{ path }}'
        targetRevision: 'main'
        plugin:
          name: argocd-lovely-plugin
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
