apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: domino
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Domino project
  destinations:
    # explicitly deny deployments to kube-system & argocd namespaces
  - namespace: '!kube-system'
    server: '*'
  - namespace: 'arcocd'
    server: '*'
    # scope project to domino-* namespaces
  - namespace: 'domino-*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: project-domino
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - clusters:
            selector:
              matchLabels:
                argocd.argoproj.io/secret-type: cluster
                workload-type: apps
        - git:
            repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples
            requeueAfterSeconds: 20
            revision: ""
            directories:
              - path: apps/**
  template:
    metadata:
      name: 'domino-app-{{ path.basename }}'
    spec:
      project: domino
      destination:
        namespace: '{{ path }}'
        server: '{{ server }}'
      source:
        repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples
        path: '{{ path }}'
        targetRevision: 'HEAD'
        plugin:
          name: argocd-lovely-plugin
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
