# Downloads the plugin and moves it to /custom-tools, which is then mounted on the argocd-repo-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-lovely-plugin
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools/helm-plugins
          subPath: helm-plugins
        env:
          - name: HELM_PLUGINS
            value: /custom-tools/helm-plugins/
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: helm-external-val-plugin-download
        args:
          - |
            mkdir -p $HELM_PLUGINS
            test -e $HELM_PLUGINS/helm-external-val || helm plugin install https://github.com/kuuji/helm-external-val
        command:
          - sh
          - -c
        image: alpine/helm:3.8.0
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
        env:
          - name: HELM_PLUGINS
            value: /custom-tools/helm-plugins/
