---
namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

components:
- ./components/argocd-lovely-plugin
- ./components/helm-external-val
