apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |-
    - name: argocd-lovely-plugin
      generate:
        command: ["argocd-lovely-plugin"]
