---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: domino-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: 'domiono-app-{{path.basename}}'
    spec:
      destination:
        namespace: domino-app-{{path.basename}}
        server: 'https://kubernetes.default.svc'
      source:
        path: '{{path}}'
        repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples
        targetRevision: HEAD
        plugin:
          name: argocd-lovely-plugin
      project: domino
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=background
          - CreateNamespace=true
